### ISSUE TITLE
Numpy strings should be a standard list of strings.

### ISSUE THREAD

**Issue by watakandai** [HIRO-group/ros_robotic_skin#100]
https://github.com/HIRO-group/ros_robotic_skin/blob/e4f225df1c341719373484e5fe0d2ba56f67212f/scripts/controllers/RobotArm.py#L185

@peasant98

**Comment by peasant98** [comment]
@watakandai - What happens when it is a numpy array? Has that been causing errors?

**Comment by peasant98** [comment]
Is this ok to close?
