### ISSUE TITLE
The data collection scripts hang up and don't respond

### ISSUE THREAD

**Issue by krishnachaitanya7** [HIRO-group/ros_robotic_skin#78]
[PandaControllerManager.py#L30](https://github.com/HIRO-group/ros_robotic_skin/blob/master/scripts/controllers/PandaControllerManager.py#L30) causes a problem. The data collection scripts rely on this line and sometimes it hangs up and doesn't respond and complete its execution. 

Ways of Reproducing: When you abruptly exit the data collection script and start again, sometimes it just stucks there and doesn't move forward. It's because python is waiting for that line to execute which never ends. Sometimes you can reproduce the issue by abruptly ending script and sometimes you don't. Try exiting the script multiple times and you can reproduce this issue.

Making a note for myself here to keep track of it.

**Comment by peasant98** [comment]
This was fixed, right @krishnachaitanya9 ?

**Comment by krishnachaitanya7** [comment]
Yes. Closing it.
